/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTurmasRouteImport } from './routes/_authenticated/turmas'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedNotasRouteImport } from './routes/_authenticated/notas'
import { Route as AuthenticatedHorariosRouteImport } from './routes/_authenticated/horarios'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedEntregasRouteImport } from './routes/_authenticated/entregas'
import { Route as AuthenticatedCalendarioRouteImport } from './routes/_authenticated/calendario'
import { Route as AuthenticatedAvisosRouteImport } from './routes/_authenticated/avisos'
import { Route as AuthenticatedAtividadesRouteImport } from './routes/_authenticated/atividades'
import { Route as AuthenticatedTurmasIdRouteImport } from './routes/_authenticated/turmas.$id'
import { Route as AuthenticatedAtividadesNovaRouteImport } from './routes/_authenticated/atividades.nova'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin.usuarios'
import { Route as AuthenticatedAdminTurmasRouteImport } from './routes/_authenticated/admin.turmas'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTurmasRoute = AuthenticatedTurmasRouteImport.update({
  id: '/turmas',
  path: '/turmas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotasRoute = AuthenticatedNotasRouteImport.update({
  id: '/notas',
  path: '/notas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHorariosRoute = AuthenticatedHorariosRouteImport.update({
  id: '/horarios',
  path: '/horarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEntregasRoute = AuthenticatedEntregasRouteImport.update({
  id: '/entregas',
  path: '/entregas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarioRoute = AuthenticatedCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAvisosRoute = AuthenticatedAvisosRouteImport.update({
  id: '/avisos',
  path: '/avisos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAtividadesRoute = AuthenticatedAtividadesRouteImport.update({
  id: '/atividades',
  path: '/atividades',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTurmasIdRoute = AuthenticatedTurmasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedTurmasRoute,
} as any)
const AuthenticatedAtividadesNovaRoute =
  AuthenticatedAtividadesNovaRouteImport.update({
    id: '/nova',
    path: '/nova',
    getParentRoute: () => AuthenticatedAtividadesRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/admin/usuarios',
    path: '/admin/usuarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminTurmasRoute =
  AuthenticatedAdminTurmasRouteImport.update({
    id: '/admin/turmas',
    path: '/admin/turmas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/atividades': typeof AuthenticatedAtividadesRouteWithChildren
  '/avisos': typeof AuthenticatedAvisosRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/entregas': typeof AuthenticatedEntregasRoute
  '/home': typeof AuthenticatedHomeRoute
  '/horarios': typeof AuthenticatedHorariosRoute
  '/notas': typeof AuthenticatedNotasRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/turmas': typeof AuthenticatedTurmasRouteWithChildren
  '/admin/turmas': typeof AuthenticatedAdminTurmasRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/atividades/nova': typeof AuthenticatedAtividadesNovaRoute
  '/turmas/$id': typeof AuthenticatedTurmasIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/atividades': typeof AuthenticatedAtividadesRouteWithChildren
  '/avisos': typeof AuthenticatedAvisosRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/entregas': typeof AuthenticatedEntregasRoute
  '/home': typeof AuthenticatedHomeRoute
  '/horarios': typeof AuthenticatedHorariosRoute
  '/notas': typeof AuthenticatedNotasRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/turmas': typeof AuthenticatedTurmasRouteWithChildren
  '/admin/turmas': typeof AuthenticatedAdminTurmasRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/atividades/nova': typeof AuthenticatedAtividadesNovaRoute
  '/turmas/$id': typeof AuthenticatedTurmasIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/atividades': typeof AuthenticatedAtividadesRouteWithChildren
  '/_authenticated/avisos': typeof AuthenticatedAvisosRoute
  '/_authenticated/calendario': typeof AuthenticatedCalendarioRoute
  '/_authenticated/entregas': typeof AuthenticatedEntregasRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/horarios': typeof AuthenticatedHorariosRoute
  '/_authenticated/notas': typeof AuthenticatedNotasRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/turmas': typeof AuthenticatedTurmasRouteWithChildren
  '/_authenticated/admin/turmas': typeof AuthenticatedAdminTurmasRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/atividades/nova': typeof AuthenticatedAtividadesNovaRoute
  '/_authenticated/turmas/$id': typeof AuthenticatedTurmasIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/atividades'
    | '/avisos'
    | '/calendario'
    | '/entregas'
    | '/home'
    | '/horarios'
    | '/notas'
    | '/perfil'
    | '/turmas'
    | '/admin/turmas'
    | '/admin/usuarios'
    | '/atividades/nova'
    | '/turmas/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/atividades'
    | '/avisos'
    | '/calendario'
    | '/entregas'
    | '/home'
    | '/horarios'
    | '/notas'
    | '/perfil'
    | '/turmas'
    | '/admin/turmas'
    | '/admin/usuarios'
    | '/atividades/nova'
    | '/turmas/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/atividades'
    | '/_authenticated/avisos'
    | '/_authenticated/calendario'
    | '/_authenticated/entregas'
    | '/_authenticated/home'
    | '/_authenticated/horarios'
    | '/_authenticated/notas'
    | '/_authenticated/perfil'
    | '/_authenticated/turmas'
    | '/_authenticated/admin/turmas'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/atividades/nova'
    | '/_authenticated/turmas/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/turmas': {
      id: '/_authenticated/turmas'
      path: '/turmas'
      fullPath: '/turmas'
      preLoaderRoute: typeof AuthenticatedTurmasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notas': {
      id: '/_authenticated/notas'
      path: '/notas'
      fullPath: '/notas'
      preLoaderRoute: typeof AuthenticatedNotasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/horarios': {
      id: '/_authenticated/horarios'
      path: '/horarios'
      fullPath: '/horarios'
      preLoaderRoute: typeof AuthenticatedHorariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entregas': {
      id: '/_authenticated/entregas'
      path: '/entregas'
      fullPath: '/entregas'
      preLoaderRoute: typeof AuthenticatedEntregasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendario': {
      id: '/_authenticated/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof AuthenticatedCalendarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/avisos': {
      id: '/_authenticated/avisos'
      path: '/avisos'
      fullPath: '/avisos'
      preLoaderRoute: typeof AuthenticatedAvisosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/atividades': {
      id: '/_authenticated/atividades'
      path: '/atividades'
      fullPath: '/atividades'
      preLoaderRoute: typeof AuthenticatedAtividadesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/turmas/$id': {
      id: '/_authenticated/turmas/$id'
      path: '/$id'
      fullPath: '/turmas/$id'
      preLoaderRoute: typeof AuthenticatedTurmasIdRouteImport
      parentRoute: typeof AuthenticatedTurmasRoute
    }
    '/_authenticated/atividades/nova': {
      id: '/_authenticated/atividades/nova'
      path: '/nova'
      fullPath: '/atividades/nova'
      preLoaderRoute: typeof AuthenticatedAtividadesNovaRouteImport
      parentRoute: typeof AuthenticatedAtividadesRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/turmas': {
      id: '/_authenticated/admin/turmas'
      path: '/admin/turmas'
      fullPath: '/admin/turmas'
      preLoaderRoute: typeof AuthenticatedAdminTurmasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedAtividadesRouteChildren {
  AuthenticatedAtividadesNovaRoute: typeof AuthenticatedAtividadesNovaRoute
}

const AuthenticatedAtividadesRouteChildren: AuthenticatedAtividadesRouteChildren =
  {
    AuthenticatedAtividadesNovaRoute: AuthenticatedAtividadesNovaRoute,
  }

const AuthenticatedAtividadesRouteWithChildren =
  AuthenticatedAtividadesRoute._addFileChildren(
    AuthenticatedAtividadesRouteChildren,
  )

interface AuthenticatedTurmasRouteChildren {
  AuthenticatedTurmasIdRoute: typeof AuthenticatedTurmasIdRoute
}

const AuthenticatedTurmasRouteChildren: AuthenticatedTurmasRouteChildren = {
  AuthenticatedTurmasIdRoute: AuthenticatedTurmasIdRoute,
}

const AuthenticatedTurmasRouteWithChildren =
  AuthenticatedTurmasRoute._addFileChildren(AuthenticatedTurmasRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAtividadesRoute: typeof AuthenticatedAtividadesRouteWithChildren
  AuthenticatedAvisosRoute: typeof AuthenticatedAvisosRoute
  AuthenticatedCalendarioRoute: typeof AuthenticatedCalendarioRoute
  AuthenticatedEntregasRoute: typeof AuthenticatedEntregasRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedHorariosRoute: typeof AuthenticatedHorariosRoute
  AuthenticatedNotasRoute: typeof AuthenticatedNotasRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedTurmasRoute: typeof AuthenticatedTurmasRouteWithChildren
  AuthenticatedAdminTurmasRoute: typeof AuthenticatedAdminTurmasRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAtividadesRoute: AuthenticatedAtividadesRouteWithChildren,
  AuthenticatedAvisosRoute: AuthenticatedAvisosRoute,
  AuthenticatedCalendarioRoute: AuthenticatedCalendarioRoute,
  AuthenticatedEntregasRoute: AuthenticatedEntregasRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedHorariosRoute: AuthenticatedHorariosRoute,
  AuthenticatedNotasRoute: AuthenticatedNotasRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedTurmasRoute: AuthenticatedTurmasRouteWithChildren,
  AuthenticatedAdminTurmasRoute: AuthenticatedAdminTurmasRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
